import { z } from "zod";

export const contactFormSchema = z.object({
  full_name: z.string().min(2, "Name must be at least 2 characters"),
  email: z.string().email("Invalid email address"),
  phone: z.string().optional(),
  country_code: z.string().default("+1"),
  company_name: z.string().optional(),
  inquiry_type: z.enum(["AI_AUTOMATION", "VOICE_ASSISTANT", "CHATBOT", "GENERAL"]),
  message: z.string().min(10, "Message must be at least 10 characters"),
  preferred_contact: z.enum(["EMAIL", "PHONE", "NO_PREFERENCE"]),
  referral_source: z.enum(["GOOGLE_SEARCH", "SOCIAL_MEDIA", "REFERRAL", "ADVERTISEMENT", "OTHER"]).optional(),
  consent_given: z.boolean().refine((val) => val === true, "You must agree to the terms"),
});

export type ContactFormValues = z.infer<typeof contactFormSchema>;

export const countryCodes = [
  { value: "+1", label: "United States (+1)" },
  { value: "+44", label: "United Kingdom (+44)" },
  { value: "+91", label: "India (+91)" },
  { value: "+86", label: "China (+86)" },
  { value: "+81", label: "Japan (+81)" },
  { value: "+49", label: "Germany (+49)" },
  { value: "+33", label: "France (+33)" },
  { value: "+61", label: "Australia (+61)" },
  { value: "+7", label: "Russia (+7)" },
  { value: "+55", label: "Brazil (+55)" },
  { value: "+34", label: "Spain (+34)" },
  { value: "+39", label: "Italy (+39)" },
  { value: "+31", label: "Netherlands (+31)" },
  { value: "+48", label: "Poland (+48)" },
  { value: "+46", label: "Sweden (+46)" },
  { value: "+47", label: "Norway (+47)" },
  { value: "+45", label: "Denmark (+45)" },
  { value: "+358", label: "Finland (+358)" },
  { value: "+43", label: "Austria (+43)" },
  { value: "+32", label: "Belgium (+32)" },
  { value: "+41", label: "Switzerland (+41)" },
  { value: "+351", label: "Portugal (+351)" },
  { value: "+353", label: "Ireland (+353)" },
  { value: "+30", label: "Greece (+30)" },
  { value: "+36", label: "Hungary (+36)" },
  { value: "+420", label: "Czech Republic (+420)" },
  { value: "+65", label: "Singapore (+65)" },
  { value: "+82", label: "South Korea (+82)" },
  { value: "+852", label: "Hong Kong (+852)" },
  { value: "+886", label: "Taiwan (+886)" },
  { value: "+84", label: "Vietnam (+84)" },
  { value: "+66", label: "Thailand (+66)" },
  { value: "+63", label: "Philippines (+63)" },
  { value: "+60", label: "Malaysia (+60)" },
  { value: "+62", label: "Indonesia (+62)" },
  { value: "+971", label: "United Arab Emirates (+971)" },
  { value: "+966", label: "Saudi Arabia (+966)" },
  { value: "+972", label: "Israel (+972)" },
  { value: "+90", label: "Turkey (+90)" },
  { value: "+27", label: "South Africa (+27)" },
  { value: "+20", label: "Egypt (+20)" },
  { value: "+234", label: "Nigeria (+234)" },
  { value: "+254", label: "Kenya (+254)" },
  { value: "+52", label: "Mexico (+52)" },
  { value: "+54", label: "Argentina (+54)" },
  { value: "+56", label: "Chile (+56)" },
  { value: "+57", label: "Colombia (+57)" },
  { value: "+51", label: "Peru (+51)" },
  { value: "+58", label: "Venezuela (+58)" },
  { value: "+64", label: "New Zealand (+64)" },
] as const;