// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvhkzsqsrwnivymvnuwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2aGt6c3FzcnduaXZ5bXZudXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzNzc2NDIsImV4cCI6MjA1MTk1MzY0Mn0.CyZNQzTSlI7CwQWPSu_7zDf1xzazQvc9U-6UofHL2mw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);